# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.64.1"

default_platform :ios

app = "TurnoClase"

#ENV["DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS"] = "-t Signiant"

platform :ios do

  desc "Crear y subir capturas"
  lane :capturas do

    if prompt(text: "Modo prueba (sólo un iPhone 11 Pro) (s|n): ").downcase == "s"
      dispositivos = ["iPhone 11 Pro"]
    else
      dispositivos = [
          "iPhone SE",
          "iPhone 8",
          "iPhone 8 Plus",
          "iPhone 11 Pro",
          "iPhone 11 Pro Max",
          "iPad Pro (12.9-inch) (3rd generation)",
          "iPad Pro (12.9-inch) (2nd generation)",
      ]
    end

    if prompt(text: "Localizado (s|n): ").downcase == "s"
      idiomas = ["en-US", "es-ES"]
    else
      idiomas = ["en-US"]
    end

    subir_appstore = prompt(text: "Subirlas a la App Store (s|n): ").downcase == "s"

    snapshot(
        skip_open_summary: true,
        devices: dispositivos,
        override_status_bar: true,
        dark_mode: false,
        localize_simulator: true,
        languages: idiomas,
        scheme: app,
        output_directory: "./fastlane/screenshots/",
        clear_previous_screenshots: true,
        workspace: "../TurnoClase.xcworkspace"
    )

    frame_screenshots

    if subir_appstore
      deliver(
          #app_version: "3.0.3",
          force: true,
          skip_binary_upload: true,
          skip_screenshots: false
      )
    end
  end

  desc "Subir una nueva versión a la App Store"
  lane :publicar do
    api_key = app_store_connect_api_key(
      key_id: "PZ4M8V34F2",
      issuer_id: "69a6de72-7482-47e3-e053-5b8c7c11a4d1",
      key_filepath: "../../private/ios/AuthKey_PZ4M8V34F2.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match(type: "appstore")
    gym(
        scheme: app,
        workspace: "../TurnoClase.xcworkspace",
        include_bitcode: false)
    deliver(
        force: true,
        automatic_release: true,
        skip_screenshots: true,
        submission_information: {
            add_id_info_uses_idfa: false
        },
    	precheck_include_in_app_purchases: false
    )
  end

  desc "Renovar los certificados de la App Store"
  lane :certificados do
    api_key = app_store_connect_api_key(
      key_id: "PZ4M8V34F2",
      issuer_id: "69a6de72-7482-47e3-e053-5b8c7c11a4d1",
      key_filepath: "../../private/ios/AuthKey_PZ4M8V34F2.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    match_nuke(type: "appstore")
  end
end


# More information about multiple platforms in fastlane: https://docs.fastlane.tools/advanced/#control-configuration-by-lane-and-by-platform
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
