# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone SE",
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone XS",
  "iPhone XS Max",
  "iPad Pro (12.9-inch)",
  "iPad Pro (9.7-inch)"
])

languages([
  "es-ES",
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme "TurnoClaseProfesor"

# Where should the resulting screenshots be stored?
output_directory "./fastlane/screenshots/"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./Project.xcodeproj"
workspace "../TurnoClase.xcworkspace"

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
